version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=agendamento'
      - 'POSTGRES_PASSWORD=Admin123#'
      - 'POSTGRES_USER=admin'
      - 'PGHOST=0.0.0.0'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d agendamento"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    command: java -jar /app.jar
    # Não precisa mais das variáveis de ambiente para o banco de dados
    # pois elas estão configuradas diretamente no application.properties
    environment:
      # Configurações do mailtrap para o Spring Boot
      SPRING_MAIL_HOST: sandbox.smtp.mailtrap.io
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: 11ba6080d42a4d
      SPRING_MAIL_PASSWORD: c419d069e004fa

volumes:
  postgres_data:
